# Generated by Django 6.0.2 on 2026-02-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
