# Generated by Django 6.0.2 on 2026-02-23 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_empresa_options_alter_perfil_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.CharField(blank=True, max_length=20, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('contratista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensayos.contratista')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_toma', models.DateField(blank=True, null=True)),
                ('recibida_en_laboratorio', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.obra')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'unique_together': {('obra', 'codigo')},
            },
        ),
    ]
