# Generated by Django 6.0.2 on 2026-02-24 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEnsayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ensayo',
                'verbose_name_plural': 'Tipos de Ensayo',
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, related_name='obras_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.muestra')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensayos.tipoensayo')),
            ],
            options={
                'verbose_name': 'Ensayo',
                'verbose_name_plural': 'Ensayos',
            },
        ),
        migrations.CreateModel(
            name='EnsayoGranulometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ensayo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ensayos.ensayo')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTamiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamiz', models.CharField(max_length=50)),
                ('peso_retenido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ensayo_granulometria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='ensayos.ensayogranulometria')),
            ],
        ),
    ]
