# Generated by Django 6.0.2 on 2026-02-24 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0002_tipoensayo_obra_tecnicos_ensayo_ensayogranulometria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayo',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos', to='ensayos.muestra'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ensayos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ensayogranulometria',
            name='ensayo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='granulometria', to='ensayos.ensayo'),
        ),
    ]
