# Generated by Django 6.0.2 on 2026-02-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0003_alter_ensayo_muestra_alter_ensayo_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoensayo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
