# Generated by Django 6.0.2 on 2026-02-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0004_tipoensayo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoensayo',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
