# Generated by Django 6.0.2 on 2026-02-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0005_alter_tipoensayo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensayogranulometria',
            name='peso_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
