# Generated by Django 6.0.2 on 2026-02-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0006_alter_ensayogranulometria_peso_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado'), ('VALIDADO', 'Validado')], default='PENDIENTE', max_length=20),
        ),
    ]
