# Generated by Django 6.0.2 on 2026-02-28 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0007_ensayo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cantera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Cantera',
                'verbose_name_plural': 'Canteras',
            },
        ),
        migrations.AddField(
            model_name='muestra',
            name='procedencia',
            field=models.CharField(choices=[('CANTERA', 'Cantera'), ('ACOPIO', 'Acopio en obra')], default='CANTERA', max_length=10),
        ),
        migrations.AddField(
            model_name='obra',
            name='numero_expediente',
            field=models.CharField(default='3062-M-2025', help_text='Ej: 3062-M-2025', max_length=50),
        ),
        migrations.AddField(
            model_name='obra',
            name='numero_licitacion',
            field=models.CharField(blank=True, default='30/2025 SIOySP', help_text='Ej: 30/2025 SIOySP', max_length=50),
        ),
        migrations.AddField(
            model_name='obra',
            name='tipo_contratacion',
            field=models.CharField(choices=[('LP', 'Licitación Pública'), ('LR', 'Licitación Privada'), ('CP', 'Concurso Privado'), ('CD', 'Contratación Directa')], default='LP', max_length=2),
        ),
        migrations.AddField(
            model_name='muestra',
            name='cantera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ensayos.cantera'),
        ),
        migrations.AddField(
            model_name='obra',
            name='cantera',
            field=models.ManyToManyField(related_name='obras', to='ensayos.cantera'),
        ),
        migrations.CreateModel(
            name='ProctorReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('densidad_maxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humedad_optima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente', models.BooleanField(default=True)),
                ('cantera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctores', to='ensayos.cantera')),
            ],
        ),
        migrations.CreateModel(
            name='EnsayoDensidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('densidad_obtenida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ensayos.cantera')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.obra')),
                ('proctor_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensayos.proctorreferencia')),
            ],
        ),
    ]
