# Generated by Django 6.0.2 on 2026-02-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0008_cantera_muestra_procedencia_obra_numero_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='procedencia',
            field=models.CharField(choices=[('CANTERA', 'Cantera'), ('ACOPIO', 'Acopio en obra')], max_length=10),
        ),
        migrations.AlterField(
            model_name='obra',
            name='numero_expediente',
            field=models.CharField(help_text='Ej: 3062-M-2025', max_length=50),
        ),
        migrations.AlterField(
            model_name='obra',
            name='numero_licitacion',
            field=models.CharField(blank=True, help_text='Ej: 30/2025 SIOySP', max_length=50),
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo_contratacion',
            field=models.CharField(choices=[('LP', 'Licitación Pública'), ('LR', 'Licitación Privada'), ('CP', 'Concurso Privado'), ('CD', 'Contratación Directa')], max_length=2),
        ),
    ]
