# Generated by Django 6.0.2 on 2026-03-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0009_alter_muestra_procedencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='cantera',
            field=models.ManyToManyField(blank=True, related_name='obras', to='ensayos.cantera'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='numero_expediente',
            field=models.CharField(blank=True, help_text='Ej: 3062-M-2025', max_length=50),
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo_contratacion',
            field=models.CharField(blank=True, choices=[('LP', 'Licitación Pública'), ('LR', 'Licitación Privada'), ('CP', 'Concurso Privado'), ('CD', 'Contratación Directa')], max_length=2),
        ),
    ]
