# Generated by Django 6.0.2 on 2026-03-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0010_alter_obra_cantera_alter_obra_numero_expediente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='numero_expediente',
            field=models.CharField(blank=True, help_text='Ej: 3062-M-2025', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='numero_licitacion',
            field=models.CharField(blank=True, help_text='Ej: 30/2025 SIOySP', max_length=50, unique=True),
        ),
    ]
