# Generated by Django 6.0.2 on 2026-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0011_alter_obra_nombre_alter_obra_numero_expediente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratista',
            old_name='contacto',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='contratista',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contratista',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contratista',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
