# Generated by Django 6.0.2 on 2026-03-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0012_rename_contacto_contratista_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='contratistas/logos/'),
        ),
    ]
